### PR TITLE
Update French translation

### PR DESCRIPTION
**Pull request by trebmuh**

### CODE REVIEW

**Comment by trebmuh** [comment]
Thanks for your quickness. :+1:

**Comment by XRevan86** [comment]
@trebmuh, de rien :-).

**Comment by soreau** [comment]
This was not properly build tested. Please see https://gitlab.com/compiz/compiz-core/commit/91ad2cc0ff33ab285850af1ea80bd714d8c72934

**Comment by trebmuh** [comment]
@soreau I've checked your link and I can see that there is a missing " character on line 692.

**Comment by soreau** [comment]
@trebmuh Between lines 692-698 of fr.po, there were two missing quotation marks.

**Comment by trebmuh** [comment]
(_crossed-edition_)

Please see https://github.com/compiz-reloaded/compiz/pull/129 which corrects the 2 missing characters.

**Pull request merged**
